credentials:
  usernames:
    bhavya:
      email: bhavya@gmail.com
      name: Bhavya T
      password: bv321 # To be replaced with hashed password
    mayank:
      email: mayank@gmail.com
      name: mayank sri
      password: mayan$%! # To be replaced with hashed password
    govin:
      email: govind@gmail.com
      name: govind k
      password: govin&^#
    naryana:
      email: narayana@gmail.com
      name: narayana d
      password: narayan@!#
cookie:
  expiry_days: 30
  key: retail_dashboard_app # Must be string
  name: retail_cookie
preauthorized:
  emails:
  - devpnarayana@gmail.com
